"use strict";
const state={sequence:0,paused:false,queued:[],overflowed:false,snapshot:null,source:null,historyRun:0,historyLoaded:0,historyTotal:0};
const MAX_QUEUE=2000,FRAME_KEY="new-divergence-live-frame-state-v2",MAX_GAP_MS=90000;
const HISTORY_CHUNK=window.innerWidth<=760?1000:window.innerWidth<=1180?1500:2500;
let profilePending=false,bootstrapPending=false,latestCommentary=null;
const $=selector=>document.querySelector(selector), finite=value=>Number.isFinite(Number(value));
const time=value=>{const n=Date.parse(value);return Number.isFinite(n)?n:null};
const number=(value,digits=0)=>finite(value)?Number(value).toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";
const shortTime=value=>{const n=time(value);return n==null?"—":new Date(n).toLocaleTimeString("en-IN",{hour12:false,timeZone:"Asia/Kolkata"});};
const colour=family=>family.startsWith("CE_")?"#ff906f":family.startsWith("PE_")?"#4bd59b":family.startsWith("FUT_")?"#f7c34d":"#2bc2ff";
function canvasSize(canvas){const ratio=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(),max=canvas.closest(".frame-maximized"),h=max?Math.max(240,max.clientHeight-105):Number(canvas.dataset.logicalHeight||260);canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(h*ratio));canvas.style.height=`${h}px`;const ctx=canvas.getContext("2d");ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w:rect.width,h};}
function selectedControls(){const profile=state.snapshot?.profile||{},all=Object.values(profile.visible_intraday_inventory||{});if(!$("#scopeID")?.checked)return[];return all.filter(row=>{const f=String(row.family);if(f==="BN_REF_FUT_VOLUME_VPOC")return $("#showVolume").checked&&$("#showVpoc").checked;if(f.startsWith("FUT_"))return $("#showOi").checked&&$("#showFutures").checked;if(f.startsWith("CE_"))return $("#showOi").checked&&$("#showCe").checked;if(f.startsWith("PE_"))return $("#showOi").checked&&$("#showPe").checked;return false;});}
function segments(rows){const result=[];let current=[];for(const row of rows){const t=time(row.timestamp);if(current.length&&t-time(current.at(-1).timestamp)>MAX_GAP_MS){result.push(current);current=[];}current.push(row);}if(current.length)result.push(current);return result;}
function drawPath(ctx,rows,x,y,field,stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.45;for(const group of segments(rows)){ctx.beginPath();let started=false;for(const row of group){if(!finite(row[field]))continue;const px=x(time(row.timestamp)),py=y(Number(row[field]));started?ctx.lineTo(px,py):ctx.moveTo(px,py);started=true;}if(started)ctx.stroke();}}
function visibleConfirmedZones(zones,asOf){return(zones||[]).filter(zone=>time(zone.confirmed_at)!=null&&time(zone.confirmed_at)<=asOf).map(zone=>{const terminal=time(zone.ended_at);return{...zone,renderEnd:terminal!=null&&terminal<=asOf?terminal:asOf,closed:terminal!=null&&terminal<=asOf};});}
function applyTransitionToZones(zones,transition){const stateName=String(transition?.state||""),episodeId=String(transition?.episode_id||""),publishedAt=transition?.published_at;if(!episodeId||time(publishedAt)==null)return;if(stateName==="CONFIRMED"){const existing=zones.find(zone=>String(zone.episode_id)===episodeId);const projected={episode_id:episodeId,colour:String(transition.colour),confirmed_at:String(publishedAt),ended_at:null,terminal_state:null};existing?Object.assign(existing,projected):zones.push(projected);return;}if(["RESOLVED","ROTATION","EXPIRED"].includes(stateName)){const open=zones.find(zone=>String(zone.episode_id)===episodeId&&zone.ended_at==null);if(open){open.ended_at=String(publishedAt);open.terminal_state=stateName;}}}
function adaptiveBasisLane(rows,priceY,priceTop,priceBottom,enabled){
  if(!enabled)return{mode:"HIDDEN",top:0,bottom:0};
  const samples=rows.map(row=>({index:Number(row.index_price),futures:Number(row.futures_price),basis:Number(row.basis)})).filter(row=>Number.isFinite(row.index)&&Number.isFinite(row.futures)&&Number.isFinite(row.basis));
  if(!samples.length)return{mode:"UNAVAILABLE",top:0,bottom:0};
  const sign=Math.sign(samples.at(-1).basis),oneSided=sign!==0&&samples.every(row=>Math.sign(row.basis)===sign);
  const upper=samples.map(row=>Math.min(priceY(row.index),priceY(row.futures))),lower=samples.map(row=>Math.max(priceY(row.index),priceY(row.futures)));
  const corridorTop=Math.max(...upper)+9,corridorBottom=Math.min(...lower)-9;
  const requestedLaneHeight=180;
  if(oneSided&&corridorBottom-corridorTop>=requestedLaneHeight){const centre=(corridorTop+corridorBottom)/2;return{mode:"BETWEEN",top:centre-requestedLaneHeight/2,bottom:centre+requestedLaneHeight/2};}
  return{mode:"TOP",top:priceTop,bottom:Math.min(priceBottom,priceTop+requestedLaneHeight)};
}
function drawBasisLane(ctx,w,left,right,rows,x,lane){
  if(!lane||lane.mode==="HIDDEN"||lane.mode==="UNAVAILABLE")return;
  const values=rows.map(row=>Number(row.basis)).filter(Number.isFinite);if(!values.length)return;
  let lo=Math.min(...values),hi=Math.max(...values);const pad=Math.max((hi-lo)*.12,.5);lo-=pad;hi+=pad;
  const laneHeight=lane.bottom-lane.top,y=value=>lane.top+8+(hi-value)/(hi-lo||1)*Math.max(1,laneHeight-16);
  ctx.save();ctx.fillStyle="rgba(17,28,48,.93)";ctx.fillRect(left,lane.top,w-left-right,laneHeight);ctx.strokeStyle="rgba(183,156,255,.28)";ctx.strokeRect(left,lane.top,w-left-right,laneHeight);ctx.font="9px ui-monospace";ctx.textAlign="right";ctx.textBaseline="middle";for(let guide=1;guide<=4;guide+=1){const fraction=guide/5,guideY=lane.top+laneHeight*fraction,guideValue=hi-(hi-lo)*fraction;ctx.strokeStyle="rgba(183,156,255,.24)";ctx.beginPath();ctx.moveTo(left,guideY);ctx.lineTo(w-right,guideY);ctx.stroke();ctx.fillStyle="rgba(212,197,255,.72)";ctx.fillText(number(guideValue,1),w-right-5,guideY-7);}
  ctx.save();ctx.beginPath();ctx.rect(left,lane.top,w-left-right,laneHeight);ctx.clip();drawPath(ctx,rows,x,y,"basis","#b79cff");ctx.restore();
  const latest=values.at(-1);ctx.fillStyle="#d4c5ff";ctx.font="10px ui-monospace";ctx.textAlign="left";ctx.textBaseline="top";ctx.fillText(`BASIS · FUT − INDEX · ${latest>=0?"+":""}${number(latest,1)} · ${lane.mode}`,left+6,lane.top+4);ctx.textBaseline="alphabetic";ctx.restore();
}
function marketChart(){
  const canvas=$("#marketChart"),{ctx,w,h}=canvasSize(canvas),rows=state.snapshot?.observations||[],controls=selectedControls();ctx.clearRect(0,0,w,h);if(!rows.length)return"UNAVAILABLE";
  const left=54,right=112,top=14,bottom=24,priceBottom=h-bottom;
  const start=time(rows[0].timestamp),end=time(rows.at(-1).timestamp)||start+1,x=t=>left+(t-start)*(w-left-right)/Math.max(1,end-start),zones=visibleConfirmedZones(state.snapshot?.confirmed_zones||[],end);
  const values=rows.flatMap(row=>[Number(row.index_price),Number(row.futures_price)]).filter(Number.isFinite);values.push(...controls.map(row=>Number(row.control_value)).filter(Number.isFinite));let lo=Math.min(...values),hi=Math.max(...values);const pad=(hi-lo||1)*.06;lo-=pad;hi+=pad;
  const preliminaryY=value=>top+(hi-value)*(priceBottom-top)/(hi-lo||1);let lane=adaptiveBasisLane(rows,preliminaryY,top,priceBottom,$("#showBasisLane")?.checked!==false);const priceTop=lane.mode==="TOP"?lane.bottom+8:top,priceY=value=>priceTop+(hi-value)*(priceBottom-priceTop)/(hi-lo||1);if(lane.mode==="BETWEEN")lane=adaptiveBasisLane(rows,priceY,priceTop,priceBottom,true);
  for(const zone of zones){const zoneStart=Math.max(start,time(zone.confirmed_at)),zoneEnd=Math.min(end,zone.renderEnd);if(zoneEnd<zoneStart||end===start)continue;ctx.fillStyle=zone.colour==="GREEN"?"rgba(75,213,155,.10)":"rgba(255,100,131,.11)";ctx.fillRect(x(zoneStart),priceTop,Math.max(1,x(zoneEnd)-x(zoneStart)),priceBottom-priceTop);}
  ctx.strokeStyle="#17384a";ctx.fillStyle="#8eb0c1";ctx.font="10px ui-monospace";for(let i=0;i<5;i++){const py=priceTop+i*(priceBottom-priceTop)/4;ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(w-right,py);ctx.stroke();ctx.fillText(number(hi-i*(hi-lo)/4,0),4,py+3);}
  drawBasisLane(ctx,w,left,right,rows,x,lane);drawPath(ctx,rows,x,priceY,"index_price","#2bc2ff");drawPath(ctx,rows,x,priceY,"futures_price","#e7edf0");
  for(const row of controls){const value=Number(row.control_value),py=priceY(value),c=colour(String(row.family));ctx.save();ctx.strokeStyle=c;ctx.globalAlpha=.9;ctx.setLineDash(String(row.family).includes("NEG")?[5,4]:[]);ctx.beginPath();ctx.moveTo(left,py);ctx.lineTo(w-right,py);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=c;ctx.font="10px ui-monospace";ctx.fillText(`${String(row.family).replaceAll("_"," ")} ${number(value)}`,w-right+5,py+3);ctx.restore();}
  const valid=(state.snapshot?.profile?.futures_oi||[]).filter(row=>finite(row.oi)&&time(row.t)!=null&&time(row.t)>=start&&time(row.t)<=end),deltaZeroY=priceBottom-23;
  if(valid.length){let oiLo=Math.min(...valid.map(row=>Number(row.oi))),oiHi=Math.max(...valid.map(row=>Number(row.oi)));const oiPad=Math.max((oiHi-oiLo)*.08,1);oiLo-=oiPad;oiHi+=oiPad;const oiOverlayTop=priceTop+22,oiOverlayBottom=Math.max(oiOverlayTop+1,priceBottom-48),oiY=value=>oiOverlayTop+(oiHi-value)*(oiOverlayBottom-oiOverlayTop)/(oiHi-oiLo||1);ctx.strokeStyle="#f7c34d";ctx.lineWidth=1.6;ctx.beginPath();let begun=false,prior=null;for(const row of valid){const receipt=time(row.t),point=[x(receipt),oiY(Number(row.oi))];if(!begun||prior===null||receipt-prior>MAX_GAP_MS||row.d===null)ctx.moveTo(...point);else ctx.lineTo(...point);begun=true;prior=receipt;}ctx.stroke();ctx.fillStyle="#f7c34d";ctx.textAlign="left";ctx.fillText(`FUT OI ${number(valid.at(-1).oi)}`,left+5,priceTop+13);ctx.textAlign="right";ctx.fillText(`OI ${number(oiHi)}`,w-right-4,priceTop+11);ctx.fillText(`OI ${number(oiLo)}`,w-right-4,priceBottom-5);ctx.textAlign="left";
    const deltas=valid.map(row=>Number(row.d)).filter(Number.isFinite),maximum=Math.max(1,...deltas.map(Math.abs)),barWidth=Math.max(1,Math.min(6,(w-left-right)/Math.max(valid.length,1)*.72));ctx.strokeStyle="#31566a";ctx.beginPath();ctx.moveTo(left,deltaZeroY);ctx.lineTo(w-right,deltaZeroY);ctx.stroke();ctx.fillStyle="#8eb0c1";ctx.fillText("±ΔOI",4,deltaZeroY+3);for(const row of valid){if(row.d===null)continue;const delta=Number(row.d);if(!Number.isFinite(delta)||delta===0)continue;const barHeight=Math.max(1,Math.abs(delta)/maximum*20);ctx.fillStyle=delta>0?"#4bd59b":"#ff6483";ctx.fillRect(x(time(row.t))-barWidth/2,delta>0?deltaZeroY-barHeight:deltaZeroY,barWidth,barHeight);}}
  else{ctx.fillStyle="#8eb0c1";ctx.fillText("Futures OI unavailable",left+5,priceTop+13);}
  for(const zone of zones){const zoneStart=time(zone.confirmed_at);if(zoneStart>=start&&zoneStart<=end&&end!==start){ctx.strokeStyle=zone.colour==="GREEN"?"#4bd59b":"#ff6483";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x(zoneStart),priceTop);ctx.lineTo(x(zoneStart),priceBottom);ctx.stroke();}if(zone.closed&&zone.renderEnd>=start&&zone.renderEnd<=end){ctx.strokeStyle="#8eb0c1";ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(x(zone.renderEnd),priceTop);ctx.lineTo(x(zone.renderEnd),priceBottom);ctx.stroke();ctx.setLineDash([]);}}
  const gap=rows.findIndex((row,index)=>index>0&&time(row.timestamp)-time(rows[index-1].timestamp)>MAX_GAP_MS);if(gap>0){ctx.fillStyle="#f7c34d";ctx.font="11px system-ui";ctx.fillText("Feed gap present — chart path is intentionally broken",left,h-5);}return lane.mode;
}
function strikeChart(canvas,kind){const {ctx,w,h}=canvasSize(canvas),rows=(state.snapshot?.profile?.option_strike_oi||[]).filter(r=>r.k===kind&&finite(r.s)&&finite(r.oi)).sort((a,b)=>Number(b.s)-Number(a.s));ctx.clearRect(0,0,w,h);const status=$(`#${kind.toLowerCase()}StrikeStatus`);status.textContent=rows.length?`${rows.length} fixed strikes`:"Unavailable";if(!rows.length)return;const max=Math.max(...rows.map(r=>Number(r.oi)),1),left=52,right=58,top=12,rowH=(h-top-10)/rows.length,index=Number(state.snapshot?.observations?.at(-1)?.index_price);rows.forEach((row,i)=>{const cy=top+i*rowH+rowH/2,bw=(w-left-right)*Number(row.oi)/max;ctx.fillStyle=kind==="CE"?"#a9604e":"#367f65";ctx.fillRect(left,cy-rowH*.25,bw,rowH*.5);ctx.fillStyle="#edf7fb";ctx.font="10px ui-monospace";ctx.textAlign="right";ctx.fillText(number(row.s),left-6,cy+3);ctx.textAlign="left";ctx.fillText(number(row.oi),left+bw+5,cy+3);ctx.fillStyle=Number(row.d)>=0?"#4bd59b":"#ff6483";ctx.textAlign="right";ctx.fillText(`${Number(row.d)>=0?"+":""}${number(row.d)}`,w-3,cy+3);});if(finite(index)){const nearest=rows.reduce((a,b)=>Math.abs(Number(a.s)-index)<Math.abs(Number(b.s)-index)?a:b);const i=rows.indexOf(nearest),cy=top+i*rowH+rowH/2;ctx.strokeStyle="#2bc2ff";ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(left-3,cy);ctx.lineTo(w-right,cy);ctx.stroke();ctx.setLineDash([]);}}
function add(parent,tag,text,klass=""){const node=document.createElement(tag);node.className=klass;node.textContent=String(text);parent.append(node);return node;}
function inventory(){const controls=selectedControls(),list=$("#inventoryLevelList");list.replaceChildren();$("#inventoryVisibleCount").textContent=`${controls.length} levels shown`;$("#inventoryLevelCount").textContent=`${controls.length} shown`;$("#profileStatus").textContent=controls.length?"ID available":"ID unavailable";for(const row of controls.sort((a,b)=>Number(a.control_value)-Number(b.control_value))){const card=add(list,"div","","inventory-level-row");const swatch=add(card,"span","","inventory-level-swatch");swatch.style.setProperty("--level-colour",colour(String(row.family)));const copy=add(card,"div","","inventory-level-copy");add(copy,"strong",String(row.family).replaceAll("_"," "));add(copy,"span",`as of ${shortTime(row.t)}${row.value_area_low==null?"":` · VA ${number(row.value_area_low)}–${number(row.value_area_high)}`}`);const value=add(card,"strong",number(row.control_value),"inventory-level-value");value.style.setProperty("--level-colour",colour(String(row.family)));}}
function shifts(){const target=$("#shiftList"),history=state.snapshot?.profile?.recent_intraday_inventory_shifts||{},rows=[];for(const [family,items] of Object.entries(history)){for(let i=1;i<items.length;i++){if(Number(items[i-1].control_value)!==Number(items[i].control_value))rows.push({family,from:items[i-1].control_value,to:items[i].control_value,t:items[i].t});}}rows.sort((a,b)=>time(b.t)-time(a.t));target.replaceChildren();for(const row of rows.slice(0,10)){const card=add(target,"div","","transition-card rotation"),head=add(card,"div","","transition-head");add(head,"strong",row.family.replaceAll("_"," "));add(head,"time",shortTime(row.t));add(card,"p",`${number(row.from)} → ${number(row.to)}`);}if(!rows.length)add(target,"p","No material ID control migration yet.","empty");}
function transitions(){const target=$("#transitionList"),rows=(state.snapshot?.transitions||[]).slice(-10).reverse();target.replaceChildren();$("#transitionCount").textContent=`${rows.length} recent`;for(const row of rows){const stateName=String(row.state||row.new_state||"PUBLICATION"),card=add(target,"div","","transition-card "+(stateName.includes("RED")?"red":stateName.includes("GREEN")?"green":stateName.includes("CANDIDATE")?"candidate":"terminal")),head=add(card,"div","","transition-head");add(head,"strong",stateName.replaceAll("_"," "));add(head,"time",shortTime(row.published_at||row.at||row.timestamp));add(card,"p",row.reason_code||row.reason||row.transition_id||"Authoritative state publication");}if(!rows.length)add(target,"p","No published transition yet.","empty");}
function feed(){const latest=state.snapshot?.observations?.at(-1),age=latest?Math.max(0,(Date.now()-time(latest.timestamp))/1000):Infinity,pill=$("#feedStatus");pill.textContent=!Number.isFinite(age)?"Feed · unavailable":age<=20?`Feed · live ${age.toFixed(0)}s`:`Feed · stale ${Math.floor(age)}s`;pill.className=`state-pill ${age<=20?"green":"candidate"}`;pill.title=latest?`Latest synchronized receipt ${latest.timestamp_ist||latest.timestamp}`:"No synchronized receipt";}
function render(){const snap=state.snapshot;if(!snap)return;const latest=snap.observations.at(-1),evidence=snap.evidence.at(-1),futOi=snap.profile?.futures_oi?.at(-1);$("#clock").textContent=new Date().toLocaleString("en-IN",{timeZone:"Asia/Kolkata",hour12:false});$("#sequence").textContent=`sequence ${state.sequence} · latest receipt ${latest?shortTime(latest.timestamp):"—"}`;$("#basisState").textContent=evidence?.basis_state||"No confirmed zone";$("#marketReadout").innerHTML=latest?`<div><span>Index</span><strong>${number(latest.index_price,2)}</strong></div><div><span>Futures</span><strong>${number(latest.futures_price,2)}</strong></div><div><span>Basis</span><strong>${number(latest.basis,2)}</strong></div><div><span>Futures OI / ΔOI</span><strong>${number(futOi?.oi)} / ${finite(futOi?.d)&&Number(futOi.d)>=0?"+":""}${number(futOi?.d)}</strong></div><div><span>Sync age</span><strong>${number(latest.synchronization_age_ms)} ms</strong></div><div><span>Receipt</span><strong>${shortTime(latest.timestamp)}</strong></div>`:"";const placement=marketChart();$("#basisPlacement").textContent=placement==="BETWEEN"?"Basis lane · between Index/Futures":placement==="TOP"?"Basis lane · top":placement==="HIDDEN"?"Basis lane · hidden":"Basis lane · unavailable";strikeChart($("#ceStrikeChart"),"CE");strikeChart($("#peStrikeChart"),"PE");inventory();shifts();transitions();feed();}
function applyPublication(row){const snap=state.snapshot,event=row.event;snap.events.push(event);if(row.basis_observation)snap.observations.push(row.basis_observation);if(row.evidence)snap.evidence.push(row.evidence);snap.confirmed_zones??=[];for(const transition of(row.transitions||[]))applyTransitionToZones(snap.confirmed_zones,transition);snap.transitions.push(...row.transitions);snap.sequence=row.sequence;state.sequence=row.sequence;}
function historyLabel(text,klass="neutral"){const pill=$("#historyStatus");pill.textContent=text;pill.className=`state-pill ${klass}`;}
function mergeHistory(rows){const current=state.snapshot.observations,map=new Map(current.map(row=>[row.timestamp,row]));for(const row of rows)map.set(row.timestamp,row);state.snapshot.observations=Array.from(map.values()).sort((a,b)=>time(a.timestamp)-time(b.timestamp));}
async function hydrateHistory(before,run){if(before<=0){historyLabel(`History · complete ${number(state.historyTotal)}`,"green");return;}try{const response=await fetch(`/api/v1/live/history?before=${before}&limit=${HISTORY_CHUNK}`,{cache:"no-store"}),result=await response.json();if(run!==state.historyRun)return;if(!response.ok)throw new Error(result.error||`history ${response.status}`);mergeHistory(result.observations||[]);state.historyLoaded=Math.min(state.historyTotal,state.historyLoaded+(result.observations||[]).length);historyLabel(`History · ${number(state.historyLoaded)} / ${number(state.historyTotal)}`,"candidate");render();if(result.start>0)setTimeout(()=>hydrateHistory(result.start,run),75);else historyLabel(`History · complete ${number(state.historyTotal)}`,"green");}catch(error){if(run!==state.historyRun)return;historyLabel("History · paused, retrying","candidate");setTimeout(()=>hydrateHistory(before,run),3000);}}
async function resnapshot(){const run=++state.historyRun,response=await fetch("/api/v1/live/snapshot?max_points=1",{cache:"no-store"});if(!response.ok)throw new Error(`snapshot ${response.status}`);const snapshot=await response.json();if(run!==state.historyRun)return;state.snapshot=snapshot;state.sequence=state.snapshot.sequence;state.queued=[];state.overflowed=false;state.historyLoaded=state.snapshot.observations.length;state.historyTotal=state.snapshot.observation_count||state.historyLoaded;render();renderScenarioOnly(state.snapshot);connect();$("#connection").textContent="Browser · connected";historyLabel(state.historyTotal>state.historyLoaded?`History · ${number(state.historyLoaded)} / ${number(state.historyTotal)}`:`History · complete ${number(state.historyLoaded)}`,state.historyTotal>state.historyLoaded?"candidate":"green");if(state.historyTotal>state.historyLoaded)hydrateHistory(state.historyTotal-state.historyLoaded,run);}
async function refreshProfile(){if(!state.snapshot||profilePending)return;profilePending=true;try{const response=await fetch("/api/v1/live/profile",{cache:"no-store"}),result=await response.json();if(response.ok&&result.session===state.snapshot.session){state.snapshot.profile=result.profile;state.snapshot.backend_scenario=result.backend_scenario;render();if(latestCommentary)renderCommentary({...latestCommentary,backend_scenario:result.backend_scenario});else renderScenarioOnly(result);}}catch(error){$("#profileStatus").title=String(error);}finally{profilePending=false;}}
async function refreshCodexStatus(){const pill=$("#codexStatus");try{const response=await fetch("/api/v1/codex/status",{cache:"no-store"}),result=await response.json();const reachable=result.state==="REACHABLE_UNVERIFIED";pill.textContent=reachable?"Codex · worker reachable":"Codex · worker offline";pill.className=`state-pill ${reachable?"candidate":"neutral"}`;pill.title=result.detail||"Codex worker status";}catch(error){pill.textContent="Codex · status error";}}
function renderCommentary(result){
  const shell=$("#commentaryAnswer"),rules=result.market_profile_analysis||{},scenario=result.backend_scenario||{};shell.replaceChildren();
  const header=add(shell,"div","","commentary-summary-row");
  add(header,"strong",`${result.bias||"NO_EDGE"} · ${result.horizon_minutes||30}m`,`commentary-bias`);
  add(header,"span",`${result.confidence||"LOW"} confidence`,`state-pill neutral`);
  add(header,"span",`S ${(result.support||[]).join("/")||"—"} · R ${(result.resistance||[]).join("/")||"—"}`,"commentary-levels");
  add(shell,"p",`SHIFT · ${result.what_changed||"No fresh material control migration."}`,"commentary-shift");
  const comparison=add(shell,"div","","analysis-comparison");
  const ruleBox=add(comparison,"section","","analysis-block backend-analysis");
  add(ruleBox,"h4","Backend directional analysis");
  add(ruleBox,"strong",`${scenario.scenario||"NO_EDGE"} · ${scenario.stage||"UNRESOLVED"}`,"scenario-name");
  for(const row of (scenario.evidence||[]).slice(0,4))add(ruleBox,"p",row);
  add(ruleBox,"p",`EXPECTED · ${scenario.expected||result.possible_outcome||"No directional edge."}`,"commentary-outlook");
  add(ruleBox,"p",`CONFIRM · ${scenario.confirmation||result.confirmation||"—"}`,"commentary-invalidation");
  add(ruleBox,"p",`INVALIDATE · ${scenario.invalidation||result.invalidation||"—"}`,"commentary-invalidation");
  if((scenario.missing_evidence||[]).length)add(ruleBox,"p",`MISSING · ${scenario.missing_evidence.join(", ")}`,"commentary-warning");
  const codexBox=add(comparison,"section","","analysis-block codex-analysis");
  add(codexBox,"h4","Codex interpretation");
  add(codexBox,"p",result.summary||"Codex interpretation is unavailable for this receipt.");
  if(rules.basis_warning)add(shell,"p",`CHECK · ${rules.basis_warning}`,"commentary-warning");
  shell.hidden=false;
}
function renderScenarioOnly(result){const shell=$("#commentaryAnswer"),scenario=result.backend_scenario||{},comparison=add(document.createElement("div"),"div","","analysis-comparison"),backend=add(comparison,"section","","analysis-block backend-analysis"),codex=add(comparison,"section","","analysis-block codex-analysis");shell.replaceChildren();add(backend,"h4","Backend directional analysis");add(backend,"strong",`${scenario.scenario||"NO_EDGE"} · ${scenario.stage||"UNRESOLVED"}`,"scenario-name");for(const row of (scenario.evidence||[]).slice(0,4))add(backend,"p",row);add(backend,"p",`EXPECTED · ${scenario.expected||"No directional edge."}`,"commentary-outlook");add(backend,"p",`CONFIRM · ${scenario.confirmation||"—"}`,"commentary-invalidation");add(backend,"p",`INVALIDATE · ${scenario.invalidation||"—"}`,"commentary-invalidation");if((scenario.missing_evidence||[]).length)add(backend,"p",`MISSING · ${scenario.missing_evidence.join(", ")}`,"commentary-warning");add(codex,"h4","Codex interpretation");add(codex,"p","Press Show commentary for the latest centrally stored Codex interpretation.");shell.append(comparison);shell.hidden=false;}
async function loadCommentary(){const button=$("#showCommentary"),shell=$("#commentaryAnswer");button.disabled=true;try{const response=await fetch("/api/v1/commentary/current",{cache:"no-store"}),result=await response.json();if(response.status===202){shell.replaceChildren();add(shell,"p","Central commentary is pending; try again shortly.");shell.hidden=false;}else if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);else{latestCommentary=result;renderCommentary(result);}}catch(error){shell.replaceChildren();add(shell,"p",`Central commentary unavailable: ${error.message}`);shell.hidden=false;}finally{button.disabled=false;}}
function connect(){state.source?.close();const source=new EventSource(`/api/v1/live/stream?after=${state.sequence}`);state.source=source;source.onopen=()=>{$("#connection").textContent="Browser · connected";};source.addEventListener("publication",event=>{const row=JSON.parse(event.data);if(row.sequence!==state.sequence+1){resnapshot();return;}if(state.paused){if(!state.overflowed)state.queued.push(row);if(state.queued.length>MAX_QUEUE){state.queued=[];state.overflowed=true;}}else{applyPublication(row);render();}});source.onerror=()=>{$("#connection").textContent="Browser · reconnecting";};}
function restoreFrame(){const panel=$(".frame-maximized");panel?.classList.remove("frame-maximized");panel?.querySelector(".frame-maximize")&&(panel.querySelector(".frame-maximize").textContent="Maximize");document.body.classList.remove("has-maximized-frame");sessionStorage.removeItem("new-divergence-live-maximized");render();}
function installFrames(){document.querySelectorAll(".frame-maximize").forEach(button=>button.onclick=()=>{const panel=button.closest("section[id]");if(panel?.classList.contains("frame-maximized")){restoreFrame();return;}restoreFrame();panel?.classList.add("frame-maximized");document.body.classList.add("has-maximized-frame");sessionStorage.setItem("new-divergence-live-maximized",panel?.id||"");button.textContent="Restore";render();});const saved=JSON.parse(sessionStorage.getItem(FRAME_KEY)||"{}");document.querySelectorAll("[data-frame]").forEach(input=>{if(saved[input.dataset.frame]===false)input.checked=false;const panel=$(`#${input.dataset.frame}`);if(panel)panel.hidden=!input.checked;input.onchange=()=>{if(panel)panel.hidden=!input.checked;saved[input.dataset.frame]=input.checked;sessionStorage.setItem(FRAME_KEY,JSON.stringify(saved));render();};});document.querySelectorAll("[data-overlay]").forEach(input=>{const key=`overlay:${input.dataset.overlay}`;if(saved[key]===false)input.checked=false;input.onchange=()=>{saved[key]=input.checked;sessionStorage.setItem(FRAME_KEY,JSON.stringify(saved));render();};});window.addEventListener("keydown",event=>{if(event.key==="Escape")restoreFrame();});}
function bootstrap(){if(bootstrapPending)return;bootstrapPending=true;resnapshot().catch(error=>{$("#connection").textContent=`Browser · retrying (${error.message})`;setTimeout(bootstrap,3000);}).finally(()=>{bootstrapPending=false;});}
document.querySelectorAll(".inventory-controls input").forEach(input=>input.onchange=render);$("#pause").onclick=()=>{state.paused=true;$("#connection").textContent="Browser · view paused";};$("#resume").onclick=()=>{state.paused=false;if(state.overflowed||!state.queued.length){bootstrap();return;}state.queued.forEach(applyPublication);state.queued=[];render();};$("#showCommentary").onclick=loadCommentary;window.addEventListener("resize",render);installFrames();refreshCodexStatus();setInterval(refreshCodexStatus,30000);setInterval(refreshProfile,15000);setInterval(feed,5000);bootstrap();
