"use strict";

const state = {sequence: 0, paused: false, queued: [], overflowed: false, snapshot: null, source: null};
const MAX_QUEUE = 2000;
const frameKey = "new-divergence-live-frame-state-v1";

function canvasSize(canvas) {
  const ratio = window.devicePixelRatio || 1;
  const rect = canvas.getBoundingClientRect();
  const maximized = canvas.closest(".frame-maximized");
  const logicalHeight = maximized ? Math.max(240, maximized.clientHeight - 90) : Number(canvas.dataset.logicalHeight || 260);
  canvas.width = Math.max(1, Math.round(rect.width * ratio)); canvas.height = Math.max(1, Math.round(logicalHeight * ratio));
  canvas.style.height = `${logicalHeight}px`; const ctx = canvas.getContext("2d"); ctx.setTransform(ratio,0,0,ratio,0,0); return {ctx,w:rect.width,h:logicalHeight};
}
function lineChart(canvas, rows, field, color) {
  const {ctx,w,h}=canvasSize(canvas); ctx.clearRect(0,0,w,h); if(!rows.length)return;
  const values=rows.map(row=>Number(row[field])).filter(Number.isFinite); if(!values.length)return;
  const low=Math.min(...values), high=Math.max(...values), span=high-low||1, left=48, right=12, top=14, bottom=25;
  ctx.strokeStyle="#173a4c"; ctx.beginPath(); for(let i=0;i<5;i++){const y=top+i*(h-top-bottom)/4;ctx.moveTo(left,y);ctx.lineTo(w-right,y);}ctx.stroke();
  ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();let started=false;
  rows.forEach((row,i)=>{const value=Number(row[field]);if(!Number.isFinite(value))return;const x=left+i*Math.max(1,w-left-right)/Math.max(1,rows.length-1);const y=top+(high-value)*(h-top-bottom)/span;if(started)ctx.lineTo(x,y);else{ctx.moveTo(x,y);started=true;}});ctx.stroke();
}
function applyPublication(row) {
  const snap=state.snapshot; if(!snap)return; const event=row.event;
  snap.events.push(event); if(row.basis_observation)snap.observations.push(row.basis_observation); if(row.evidence)snap.evidence.push(row.evidence); snap.transitions.push(...row.transitions); snap.sequence=row.sequence; state.sequence=row.sequence;
}
function render() {
  const snap=state.snapshot;if(!snap)return; const observations=snap.observations;
  lineChart(document.querySelector("#marketChart"), observations, "futures_price", "#eef6fb"); lineChart(document.querySelector("#basisChart"), observations, "basis", "#b79cff");
  const latest=observations.at(-1), evidence=snap.evidence.at(-1); document.querySelector("#clock").textContent=latest?.timestamp_ist||snap.server_time; document.querySelector("#sequence").textContent=`sequence ${state.sequence} · ${snap.status}`;
  document.querySelector("#basisState").textContent=evidence?.basis_state||"Waiting for synchronized basis";
  document.querySelector("#marketReadout").innerHTML=latest?`<div><span>INDEX</span><strong>${Number(latest.index_price).toFixed(2)}</strong></div><div><span>FUTURES</span><strong>${Number(latest.futures_price).toFixed(2)}</strong></div><div><span>BASIS</span><strong>${Number(latest.basis).toFixed(2)}</strong></div>`:"";
  const option=[...snap.events].reverse().find(row=>row.kind==="OPTION_PRESSURE"); const strikes=option?.values?.strike_oi||[]; const ce=strikes.filter(row=>row.option_type==="CE").reduce((n,row)=>n+Number(row.oi||0),0), pe=strikes.filter(row=>row.option_type==="PE").reduce((n,row)=>n+Number(row.oi||0),0);
  document.querySelector("#optionReadout").innerHTML=option?`<div><span>CE OI</span><strong>${ce.toLocaleString()}</strong></div><div><span>PE OI</span><strong>${pe.toLocaleString()}</strong></div><div><span>RECEIPT</span><strong>${option.receipt_timestamp}</strong></div>`:"Waiting for option-chain receipt";
  document.querySelector("#transitionList").innerHTML=snap.transitions.slice(-12).reverse().map(row=>`<div class="inventory-level-row"><strong>${row.state}</strong><span>${row.published_at||row.at||""}</span></div>`).join("")||"No transitions";
}
async function resnapshot() { const response=await fetch("/api/v1/live/snapshot",{cache:"no-store"}); if(!response.ok)throw new Error(`snapshot ${response.status}`); state.snapshot=await response.json();state.sequence=state.snapshot.sequence;state.queued=[];state.overflowed=false;render();connect(); }
async function refreshCodexStatus(){const pill=document.querySelector("#codexStatus");try{const response=await fetch("/api/v1/codex/status",{cache:"no-store"});if(!response.ok)throw new Error(`status ${response.status}`);const result=await response.json();const ready=result.state==="REACHABLE_UNVERIFIED"&&result.prompting_enabled===true;pill.textContent=ready?"Codex · central commentary ready":result.state==="REACHABLE_UNVERIFIED"?"Codex · commentary disabled":"Codex · worker offline";pill.classList.toggle("neutral",!ready);pill.title=result.detail||"Central commentary status";}catch(error){pill.textContent="Codex · status error";pill.title=String(error);}}
function addText(parent,tag,text,klass=""){const node=document.createElement(tag);node.className=klass;node.textContent=String(text);parent.append(node);}
function renderCommentary(result){const shell=document.querySelector("#commentaryAnswer"),rules=result.market_profile_analysis||{};shell.replaceChildren();addText(shell,"h3",`${result.bias||"NO_EDGE"} · ${result.horizon_minutes||30}m · ${result.confidence||"LOW"} confidence`);addText(shell,"p",result.what_changed||"No fresh material control migration.");addText(shell,"h4","Market-profile analysis · transparent rules");const list=document.createElement("ul");for(const row of rules.observations||[]){addText(list,"li",row);}shell.append(list);addText(shell,"h4","Codex commentary");addText(shell,"p",result.summary||"No Codex summary.");addText(shell,"h4","Experimental outlook · not validated");addText(shell,"p",result.possible_outcome||"No directional edge.");addText(shell,"p",`Support: ${(result.support||[]).join(" / ")||"unavailable"} · Resistance: ${(result.resistance||[]).join(" / ")||"unavailable"}`);addText(shell,"p",`As of ${result.causal_as_of} · ${result.cached?"stored":"new central result"}`,"codex-replay-meta");shell.hidden=false;}
async function loadCommentary(){const button=document.querySelector("#showCommentary"),shell=document.querySelector("#commentaryAnswer");button.disabled=true;button.textContent="Loading…";try{const response=await fetch("/api/v1/commentary/current",{cache:"no-store"});const result=await response.json();if(!response.ok&&response.status!==202)throw new Error(result.error||`HTTP ${response.status}`);if(response.status===202){shell.replaceChildren();addText(shell,"p","Central commentary is pending; try again shortly.");shell.hidden=false;}else renderCommentary(result);}catch(error){shell.replaceChildren();addText(shell,"p",`Central commentary unavailable: ${error.message}`);shell.hidden=false;}finally{button.disabled=false;button.textContent="Show latest commentary";}}
function connect(){state.source?.close();const source=new EventSource(`/api/v1/live/stream?after=${state.sequence}`);state.source=source;source.onopen=()=>{document.querySelector("#connection").textContent="Connected";};source.addEventListener("publication",event=>{const row=JSON.parse(event.data);if(row.sequence!==state.sequence+1){resnapshot();return;}if(state.paused){if(!state.overflowed)state.queued.push(row);if(state.queued.length>MAX_QUEUE){state.queued=[];state.overflowed=true;document.querySelector("#connection").textContent="Paused · resnapshot required";}}else{applyPublication(row);render();}});source.onerror=()=>{document.querySelector("#connection").textContent="Reconnecting";};}
function restoreFrame(){const panel=document.querySelector(".frame-maximized");panel?.classList.remove("frame-maximized");panel?.querySelector(".frame-maximize")&&(panel.querySelector(".frame-maximize").textContent="Maximize");document.body.classList.remove("has-maximized-frame");sessionStorage.removeItem("new-divergence-live-maximized");render();}
function installFrames(){document.querySelectorAll("main > section[id]").forEach(panel=>{const button=document.createElement("button");button.className="frame-maximize";button.textContent="Maximize";button.onclick=()=>{restoreFrame();panel.classList.add("frame-maximized");document.body.classList.add("has-maximized-frame");sessionStorage.setItem("new-divergence-live-maximized",panel.id);button.textContent="Restore";render();};panel.append(button);});const saved=JSON.parse(sessionStorage.getItem(frameKey)||"{}");document.querySelectorAll("[data-frame]").forEach(input=>{if(saved[input.dataset.frame]===false)input.checked=false;document.querySelector(`#${input.dataset.frame}`).hidden=!input.checked;input.onchange=()=>{document.querySelector(`#${input.dataset.frame}`).hidden=!input.checked;saved[input.dataset.frame]=input.checked;sessionStorage.setItem(frameKey,JSON.stringify(saved));};});const id=sessionStorage.getItem("new-divergence-live-maximized");if(id)document.querySelector(`#${id}`)?.classList.add("frame-maximized");window.addEventListener("keydown",event=>{if(event.key==="Escape")restoreFrame();});}
document.querySelector("#pause").onclick=()=>{state.paused=true;document.querySelector("#connection").textContent="View paused";};document.querySelector("#resume").onclick=()=>{state.paused=false;if(state.overflowed||!state.queued.length){resnapshot();return;}state.queued.forEach(applyPublication);state.queued=[];render();};document.querySelector("#showCommentary").onclick=loadCommentary;
window.addEventListener("resize",render);installFrames();refreshCodexStatus();setInterval(refreshCodexStatus,30000);resnapshot().catch(error=>{document.querySelector("#connection").textContent=String(error);});
