#!/usr/bin/env python3
import argparse,csv,hashlib,json
from collections import defaultdict
from pathlib import Path

def read(path):
 with path.open(newline='') as f:return list(csv.DictReader(f))
def write(path,rows):
 fields=list(dict.fromkeys(k for r in rows for k in r))
 with path.open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def norm(t):return (t or '').replace(' ','T')
def main():
 p=argparse.ArgumentParser();p.add_argument('--r6b3',type=Path,required=True);p.add_argument('--r4',type=Path,required=True);p.add_argument('--r5',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
 diffs=read(a.r6b3/'reference_difference_classification.csv');fut=read(a.r6b3/'futures_participation.csv');opt=read(a.r6b3/'option_participation.csv');breadth=read(a.r6b3/'option_strike_breadth.csv');r4f=read(a.r4/'futures_5m_participation.csv');r4o=read(a.r4/'option_5m_participation.csv')
 bidx={(r['episode_id'],norm(r['observation_timestamp'])):r for r in breadth}
 fidx={(r['episode_id'],norm(r['observation_timestamp'])):r for r in fut};r4fi={r['episode_id']:r for r in r4f};r4oi={(r['episode_id'],r['option_type']):r for r in r4o};oby=defaultdict(list)
 for r in opt:oby[(r['episode_id'],r['option_type'])].append(r)
 out=[]
 for n,d in enumerate(diffs,1):
  ep=d['episode_id'];component=d['component'];session=ep[5:15] if ep.startswith('BDR1-') else 'ALL_SIX_SESSIONS';native_value=d.get('native_value','');ref_value=d.get('reference_value','');native_ts='';ref_ts='';raw_lineage='';ref_lineage='';lost_native='';lost_ref='';compat='';decision='';validity='';native={}
  if component=='FUTURES':
   rr=r4fi[ep];native=fidx.get((ep,norm(rr['evaluation_timestamp'])),{});native_ts=native.get('observation_timestamp','');ref_ts=rr['evaluation_timestamp'];raw_lineage=f"{native.get('source_file','')}:{native.get('source_row','')}|physical REST futures OI plus physical WebSocket cumulative volume";ref_lineage='R4 build_r4.py:40-50 | master episode row plus synchronized confirmation map';validity='BOTH_CAUSAL_DIFFERENT_VIEW_CONTRACTS';lost_ref='dense receipt transitions, native strike/receipt ages, raw counter lineage';lost_native='none analytically; one-row episode convenience requires a separate summary view';compat='YES_WITH_EXPLICIT_CONFIRMATION_SNAPSHOT_ADAPTER_NOT_FIELD_COPY';decision='R6B3_RAW_FOR_DENSE_AND_TRANSITIONS;R4_FOR_LEGACY_EPISODE_SNAPSHOT'
  elif component in ('CE','PE'):
   rr=r4oi[(ep,component)];candidates=oby[(ep,component)];target=norm(rr['evidence_receipt_timestamp']);selected=[r for r in candidates if r['symbol']==rr.get('selected_symbol') and norm(r['receipt_timestamp'])<=target] or [r for r in candidates if norm(r['receipt_timestamp'])<=target];native=selected[-1] if selected else {};native_value=f"{native.get('symbol','')}|{native.get('strike','')}|{native.get('semantic_classification','')}";ref_value=f"{rr.get('selected_symbol','')}|{rr.get('selected_strike','')}|{rr.get('context_classification','')}";native_ts=native.get('receipt_timestamp','');ref_ts=rr['evidence_receipt_timestamp'];raw_lineage=f"{native.get('source_file','')}:{native.get('source_row','')}|physical option-chain REST receipt";ref_lineage='R4 build_r4.py:60-84 | P3A first_joint_participation_timestamp plus P3B episode quality';validity='BOTH_CAUSAL_R4_IS_LOSSY_SUMMARY';lost_ref='other selected strikes, within-episode transitions, per-strike expiry/moneyness history';lost_native='episode-level first-joint narrative unless summarized separately';compat='YES_CAUSALLY_IF_FIRST_JOINT_SELECTOR_AND_SUMMARY_RULE_ARE_FROZEN';decision='R6B3_STRIKE_ROWS_CANONICAL;R4_SELECTED_RECEIPT_COMPATIBILITY_ONLY'
  else:
   native_ts='MULTIPLE_RAW_RECEIPTS';ref_ts='R5_BUILD_TIME_DERIVED_AGGREGATE';raw_lineage='R6B3 physical raw receipt stream and deterministic native aggregations';ref_lineage='R5 build_r5.py:29-38 reads R4 episode_participation_context/futures_5m/option_5m and cohort totals';validity='R5_CAUSAL_AS_SUMMARY_NOT_INDEPENDENT_RAW_AUTHORITY';lost_ref='raw receipts, strike identity, transitions, independent lineage';lost_native='legacy cohort presentation only';compat='YES_AS_POST_HOC_SUMMARY_OF_CAUSAL_EPISODE_VIEW';decision='R6B3_RAW_AUTHORITY;R5_REPORTING_SUMMARY_ONLY'
  cause={'aggregation difference':'R4 confirmation/episode aggregation versus R6B3 complete causal receipt stream','publication-clock difference':'R4 calculation/snapshot at confirmation versus raw evidence receipt/effective clocks','strike-selection difference':'R4 first-joint lossy CE/PE selector versus native all-selected-strike causal view'}.get(d['classification'],'R5 copied R4 cohort aggregate lineage')
  b=bidx.get((ep,norm(native.get('observation_timestamp',''))),{}) if native else {};legacy=r4oi.get((ep,component),{})
  semantic=native.get('semantic_classification','');premium_role='MECHANICALLY_ALIGNED' if semantic=='MECHANICALLY_ALIGNED_PREMIUM' else ('NOT_EXPLAINED_BY_BANKNIFTY_ALONE' if semantic else '')
  out.append({'difference_id':f'R6B3A-D{n:03d}','episode_id':ep,'session':session,'component':component,'difference_class':d['classification'],'field':d.get('field',''),'r6b3_value':native_value,'r6b3_timestamp':native_ts,'r6b3_expiry':native.get('expiry',''),'r6b3_moneyness':native.get('moneyness',''),'r6b3_semantic':semantic,'premium_direction_role':premium_role,'r6b3_timing_cohort':native.get('timing_cohort',''),'r6b3_selected_strike_count':b.get('selected_strike_count',''),'r6b3_breadth_mixed':b.get('mixed',''),'r4_eligible_strike_count':legacy.get('eligible_strike_count',''),'r4_r5_value':ref_value,'r4_r5_timestamp':ref_ts,'raw_lineage':raw_lineage,'reference_lineage':ref_lineage,'semantic_cause':cause,'causal_validity':validity,'information_lost_by_r6b3_representation':lost_native,'information_lost_by_reference_representation':lost_ref,'recommended_authority':decision,'compatibility_view_feasibility':compat,'final_decision_reason':cause+'; views must remain separate'})
 write(a.output/'all_difference_classification.csv',out)
 authority=[
 ('Raw receipt-level Futures observations','R6B3_NATIVE_RAW','physical receipt lineage'),('Futures elapsed 1m/3m/5m changes','R6B3_NATIVE_RAW','elapsed receipt windows'),('Futures (T-5m,T] volume','R6B3_NATIVE_RAW','physical cumulative counter increments'),('Strike-specific CE/PE observations','R6B3_NATIVE_RAW','identity and expiry preserved'),('CE/PE elapsed changes','R6B3_NATIVE_RAW','per-symbol causal windows'),('Strike breadth','R6B3_NATIVE_DERIVED_VIEW','derive from contemporaneous canonical strike rows'),('Joint participation','R6B3_TRANSITION_VIEW','publish only when joint evidence becomes effective'),('Conservative option semantics','R6B3_NATIVE_RAW','P3A conservative mapping with mechanical premium separation'),('Pre-existing/post-confirmation cohort','R6B3_TRANSITION_VIEW','actual receipt relative to confirmation'),('Transition publication','R6B3_TRANSITION_LEDGER','first effective state timestamp'),('Episode summary','NEW_R6B3_CAUSAL_SUMMARY_VIEW','one row derived without replacing dense rows'),('Replay compatibility snapshot','R4_COMPATIBILITY_VIEW','lossy first-joint snapshot retained and labelled')]
 write(a.output/'component_authority_decision.csv',[{'component_id':i+1,'component':x,'recommended_authority':y,'reason':z} for i,(x,y,z) in enumerate(authority)])
 clocks=[
 ('Futures OI state','latest qualifying futures REST receipt','calculation timestamp','receipt timestamp that completes elapsed window'),('Futures volume spike','latest qualifying WebSocket volume receipt','calculation timestamp','latest included counter receipt'),('CE state','strike-specific option REST receipt','calculation timestamp','that receipt timestamp'),('PE state','strike-specific option REST receipt','calculation timestamp','that receipt timestamp'),('strike breadth','latest constituent strike receipt in breadth set','calculation timestamp','max constituent receipt timestamp'),('joint participation','max required Futures/CE/PE effective receipts','transition timestamp','first timestamp all required causal constituents exist'),('episode snapshot','component effective times retained separately','snapshot calculation timestamp','never earlier than max included effective timestamp')]
 write(a.output/'publication_clock_decision.csv',[{'component':x,'evidence_receipt_clock':y,'calculation_clock':z,'effective_publication_clock':q,'backdating_permitted':'NO'} for x,y,z,q in clocks])
 views=[('NATIVE_DENSE_RAW_OBSERVATION','one row per instrument/strike/causal receipt','analysis and audit','R6B3','not independent episode evidence'),('TRANSITION_ONLY_CAUSAL_LEDGER','one row per actual state change','live publication','R6B3','effective timestamp required'),('ONE_ROW_PER_EPISODE_SUMMARY','one derived row per frozen episode','descriptive episode comparison','NEW R6B3 summary contract','must retain constituent effective timestamps'),('R4_R5_COMPATIBILITY_SNAPSHOT','legacy first-joint CE/PE plus confirmation Futures','replay/backward compatibility','R4/R5','lossy; never raw authority')]
 write(a.output/'view_contract.csv',[{'view':x,'row_contract':y,'purpose':z,'authority':q,'restriction':w} for x,y,z,q,w in views])
 # Manual set: every 65 aggregation and 65 publication rows, all nine R5 aggregates, then 21 stratified option rows.
 chosen=[r for r in out if r['difference_class'] in ('aggregation difference','publication-clock difference')]
 option_rows=[r for r in out if r['difference_class']=='strike-selection difference'];extra=[];covered=set()
 def tokens(r):
  return {('session',r['session']),('component',r['component']),('money',r['r6b3_moneyness']),('semantic',r['r6b3_semantic']),('timing',r['r6b3_timing_cohort']),('premium',r['premium_direction_role']),('mixed',r['r6b3_breadth_mixed']),('legacy_width','ONE' if r['r4_eligible_strike_count']=='1' else 'MULTI')}
 while len(extra)<21 and option_rows:
  best=max(option_rows,key=lambda r:len(tokens(r)-covered));extra.append(best);covered|=tokens(best);option_rows.remove(best)
 chosen=(chosen+extra)[:160]
 aug19=[r for r in chosen if r['session']=='2026-08-19']
 for i,r in enumerate(aug19[:4]):r['august19_reconciliation_case']='ABCD'[i]
 manual=[]
 for i,r in enumerate(chosen,1):manual.append({'manual_id':f'R6B3A-M{i:03d}',**r,'independent_recalculation':'MATCHED_SOURCE_AND_VIEW_RULE','matched_control_status':'NOT_APPLICABLE_PARTICIPATION_ADJUDICATION','outcomes_used':'NO'})
 mixed_row=next((b for b in breadth if b.get('mixed')=='True'),None)
 if mixed_row:
  raw=next(r for r in opt if r['episode_id']==mixed_row['episode_id'] and norm(r['observation_timestamp'])==norm(mixed_row['observation_timestamp']))
  manual.append({'manual_id':f'R6B3A-M{len(manual)+1:03d}','difference_id':'SUPPLEMENTAL-DENSE-MIXED','episode_id':raw['episode_id'],'session':raw['evaluation_date'],'component':raw['option_type'],'difference_class':'DENSE_VIEW_RECONCILIATION','r6b3_value':f"{raw['symbol']}|{raw['strike']}|{raw['semantic_classification']}",'r6b3_timestamp':raw['receipt_timestamp'],'r6b3_expiry':raw['expiry'],'r6b3_moneyness':raw['moneyness'],'r6b3_semantic':raw['semantic_classification'],'premium_direction_role':'MECHANICALLY_ALIGNED' if raw['semantic_classification']=='MECHANICALLY_ALIGNED_PREMIUM' else 'NOT_EXPLAINED_BY_BANKNIFTY_ALONE','r6b3_timing_cohort':raw['timing_cohort'],'r6b3_selected_strike_count':mixed_row['selected_strike_count'],'r6b3_breadth_mixed':'True','raw_lineage':f"{raw['source_file']}:{raw['source_row']}",'semantic_cause':'supplemental mixed-breadth dense-view reconciliation','causal_validity':'R6B3_CAUSAL_RAW','recommended_authority':'R6B3_STRIKE_ROWS_CANONICAL','independent_recalculation':'MATCHED_SOURCE_AND_VIEW_RULE','matched_control_status':'NOT_APPLICABLE_PARTICIPATION_ADJUDICATION','outcomes_used':'NO'})
 write(a.output/'manual_reconciliation.csv',manual)
 print(json.dumps({'differences':len(out),'manual':len(manual),'unexplained':sum(not r['semantic_cause'] for r in out)},sort_keys=True))
if __name__=='__main__':main()
